language: crystal
os: linux

before_install:
  # Add etcd 3.3.13
  - docker run --net="host" -p "2379:2379" -p "2380:2380" -e ALLOW_NONE_AUTHENTICATION=yes -d bitnami/etcd:3.3.13

services:
  - docker
  - redis

install:
  - shards install

script:
  # Specs
  - crystal spec --no-debug --error-trace
  # Linter
  - bin/ameba
  # Formatter
  - crystal tool format --check
